apiVersion: skaffold/v2beta22
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
      - ./infra/k8s-dev/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: auguestgao/type-reader-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: auguestgao/type-reader-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: auguestgao/type-reader-books
      context: books
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: auguestgao/type-reader-bookmark
      context: bookmark
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: auguestgao/type-reader-stats
      context: stats
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: auguestgao/type-reader-paging
      context: paging
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .