name: deploy-stats

on:
  push:
    branches:
      - main
    paths:
      - 'stats/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd stats && docker build -t auguestgao/type-reader-stats .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push auguestgao/type-reader-stats
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save type-reader-cluster
      - run: kubectl rollout restart deployment stats-depl
