name: deploy-bookmark

on:
  push:
    branches:
      - main
    paths:
      - 'bookmark/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd bookmark && docker build -t auguestgao/type-reader-bookmark .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push auguestgao/type-reader-bookmark
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save type-reader-cluster
      - run: kubectl rollout restart deployment bookmark-depl
